recorder:
    auto_purge: true
    auto_repack: true
    purge_keep_days: 30
    commit_interval: 0
    exclude:
        domains:
            - calendar
            - camera
            - input_select
            - media_player
            - number
            - persistent_notification
            - remote
            - select
            - sun
            - update
tts:
    - platform: google_translate
wake_on_lan:
zha:
    enable_quirks: true
    zigpy_config:
        ota:
            enabled: true
            extra_providers:
                - type: z2m
